EBC\PublisherClient\Campaign\Campaign:
    properties:
        id:
            type: integer
        name:
            type: string
        schedule:
            type: EBC\PublisherClient\Campaign\Schedule
        bid:
            type: EBC\PublisherClient\Campaign\Bid
        listApprovals:
            type: EBC\PublisherClient\Campaign\ListApprovals
        categories:
            type: EBC\PublisherClient\Campaign\Categories
