EBC\PublisherClient\ListDefinition\ListDefinition:
    properties:
        externalId:
            type: string
        name:
            type: string
        approvalCampaignsExceptions:
            type: EBC\PublisherClient\ListDefinition\ApprovalCampaignsExceptions
