EBC\PublisherClient\ListApprovalExceptions\ApprovalCampaignsExceptions:
    # exclude everything except what is explicitly exposed
    exclusion_policy: ALL
    properties:
        approved:
            expose: true
            type: array
        rejected:
            expose: true
            type: array
