EBC\PublisherClient\PublisherList\PublisherListStats:
    properties:
        id:
            type: string
        totalSubscribers:
            type: integer
        totalSnsubscribes:
            type: integer
        totalBounces:
            type: integer
