name: Publisher Client
baseUrl: "{scheme}://{host}{+basePath}/{publisherId}"
description: Publisher Client
operations:
    getCampaignCreativities:
        httpMethod: GET
        uri: campaigns/{campaignId}/creativities
        responseClass: 'EBC\PublisherClient\Campaign\Creativities'
        summary: Returns the creativity for one campaign
        data:
            acceptedStatusCodes: 200
        parameters:
            campaignId:
                location: uri
                description: Id of the campaign to use
                type: integer
                required: true

    getCampaigns:
        httpMethod: GET
        uri: campaigns
        responseClass: 'EBC\PublisherClient\Campaign\Campaigns'
        summary: Returns campaigns that publisher have access
        data:
            acceptedStatusCodes: 200
        parameters:
            orderBy:
                location: query
                description: How to order the result set (created|updated)
                type: string
                minLength: 2
                maxLength: 64
                required: false
                sentAs: order_by
            order:
                location: query
                description: Order asc|desc|ASC|DESC
                type: string
                minLength: 3
                maxLength: 4
                required: false
    getLists:
        httpMethod: GET
        uri: lists
        responseClass: 'EBC\PublisherClient\ListDefinition\ListsDefinition'
        summary: Returns publisher lists
        data:
            acceptedStatusCodes: 200
