#scheme: https
#host: api.emailbidding.com
#basePath: /api/p/publishers
scheme: http
host: eb.dev
basePath: /app_dev.php/api/p/publishers
request.options:
    headers:
        Accept: application/json
